# Metody analizy języka naturalnego

## Tokenizacja

In [38]:
s = 'Be yourself; everyone else is already taken.' # Oscar Wilde

Elementarna tokenizacja z wykorzystaniem `str.split()`:

In [39]:
s.split()

['Be', 'yourself;', 'everyone', 'else', 'is', 'already', 'taken.']

Bardziej zaawansowana tokenizacja z wykorzystanie wyrażeń regularnych:

In [40]:
import re
sep = r'[\s.!?,;:-]+'
re.split(sep, s)

['Be', 'yourself', 'everyone', 'else', 'is', 'already', 'taken', '']

Wykorzystanie obiektu `RegexpTokenizer` z pakietu NTLK:

In [ ]:
# !pip install nltk

In [42]:
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+|\$[\d\.]+|\S+')
tokenizer.tokenize(s)

['Be', 'yourself', ';', 'everyone', 'else', 'is', 'already', 'taken', '.']

In [43]:
tokenizer = RegexpTokenizer(r'[\s.!?,;:-]+', gaps=True)
tokenizer.tokenize(s)

['Be', 'yourself', 'everyone', 'else', 'is', 'already', 'taken']

In [44]:
s = '''He told me, "This isn't worth $10,000,000."'''

In [45]:
from nltk.tokenize import TreebankWordTokenizer

tokenizer = TreebankWordTokenizer()
tokenizer.tokenize(s)

['He',
 'told',
 'me',
 ',',
 '``',
 'This',
 'is',
 "n't",
 'worth',
 '$',
 '10,000,000',
 '.',
 "''"]

In [46]:
s = "<3 You're craaaaaazyyyyyyy! :-P Call 202-464-6903 !!!!!"

In [47]:
from nltk.tokenize import TweetTokenizer

tokenizer = TweetTokenizer(reduce_len=True)
tokenizer.tokenize(s)

['<3',
 "You're",
 'craaazyyy',
 '!',
 ':-P',
 'Call',
 '202-464-6903',
 '!',
 '!',
 '!']

## *n*-gramy
- n-gram to ciąg n elementów występujących w określonym porządku
- elementami przeważnie są słowa, choć mogą to być także sylaby, litery, itp.
- przykłady 2-gramów: (on, idzie), (idzie, do), (nie, pierwszy)
- przykłady 3-gramów: (on, idzie, tam), (Francis, Ford, Coppola)
- n-gramy pozwalają zachować informację o 
kolejności wyrazów – np. (nie, pierwszy) zachowa 
więcej informacji niż tokeny „nie” i „pierwszy”
- uwzględnianie n-gramów może znacząco 
zwiększyć słownik (zbiór tokenów)
- w praktyce odfiltrowuje się n-gramy występujące w 
zbyt małej lub zbyt dużej liczbie dokumentów

In [48]:
s = 'The United Kingdom is a country in Northwestern Europe.'

In [49]:
from nltk.util import ngrams

tokenizer = TreebankWordTokenizer()
tokens = tokenizer.tokenize(s)
list(ngrams(tokens, 2))

[('The', 'United'),
 ('United', 'Kingdom'),
 ('Kingdom', 'is'),
 ('is', 'a'),
 ('a', 'country'),
 ('country', 'in'),
 ('in', 'Northwestern'),
 ('Northwestern', 'Europe'),
 ('Europe', '.')]

## Stop listy

stop listy zawierają słowa, które występują 
często w danym języku, np. w jęz. angielskim:
- spójniki (and, or)
- rodzajniki (a, an, the)
- zaimki (this),

cd

- podczas tokenizacji słowa ze stop listy są pomijane
- argumentem za pomijaniem słów ze stop listy jest to, że nie wnoszą istotnej informacji na temat frazy
- jednak występując w n-gramie mogą dostarczać istotną informację na temat relacji między słowami
- przykład utraty części informacji z dwóch 4-gramów przy stop liście zawierającej słowa on oraz off:
		- (turn, on, the, lights) → (turn, lights)
        - (turn, off, the, lights) → (turn, lights)

In [50]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bathe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [51]:
import nltk
stop_words = nltk.corpus.stopwords.words('english')
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

## Reprezentacja 1 z n
- Reprezentacja 1 z n przechowuje tekst w postaci ciągu wektorów zero-jedynkowych
- Każdy wektor reprezentuje jeden token
- Wektory są indeksowane tokenami (pozycją tokena w słowniku tokenów)
- Na pozycji odpowiadającej tokenowi występuje wartość 1, pozostałe pozycje to 0

cd
- nie traci żadnej informacji z tekstu (jeżeli żadnej informacji nie utracił tokenizator)
- ma wysoką złożoność pamięciową– jest stosowana m.in. w sieciach neuronowych
Dokument i jego tokenizacja:

In [57]:
s = 'Be yourself; everyone else is already taken.' # Oscar Wilde
tokenizer = TreebankWordTokenizer()
tokens = tokenizer.tokenize(s) 
tokens

['Be', 'yourself', ';', 'everyone', 'else', 'is', 'already', 'taken', '.']

Utworzenie słownika (z eliminacją duplikatów):

In [58]:
vocabulary = sorted(list(set(tokens)))
vocabulary

['.', ';', 'Be', 'already', 'else', 'everyone', 'is', 'taken', 'yourself']

Utworzenie reprezentacji 1 z *n* w tablicy NumPy:

In [ ]:
# !pip install numpy

In [60]:
import numpy as np

one_hot_sentence = np.zeros([len(tokens), len(vocabulary)])
for i, word in enumerate(tokens):
    one_hot_sentence[i, vocabulary.index(word)] = 1
one_hot_sentence

array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])

Czytelniejsza wersja w postaci ramki danych Pandas:

In [ ]:
# !pip install pandas

In [64]:
import pandas as pd
df = pd.DataFrame(one_hot_sentence.astype(int), columns=vocabulary)
df

   .  ;  Be  already  else  everyone  is  taken  yourself
0  0  0   1        0     0         0   0      0         0
1  0  0   0        0     0         0   0      0         1
2  0  1   0        0     0         0   0      0         0
3  0  0   0        0     0         1   0      0         0
4  0  0   0        0     1         0   0      0         0
5  0  0   0        0     0         0   1      0         0
6  0  0   0        1     0         0   0      0         0
7  0  0   0        0     0         0   0      1         0
8  1  0   0        0     0         0   0      0         0

## Reprezentacja BoW
- Reprezentacja BoW (Bag of Words – worek słów)
- przechowuje tekst w postaci wektora
- Każdy wektor reprezentuje jeden dokument
- Wektory są indeksowane tokenami
- Na pozycji odpowiadającej tokenowi występuje częstość występowania tego tokena w dokumencie

cd
- ma mniejszą złożoność pamięciową niż 1 z n
- nie zachowuje informacji o kolejności słów
- wykorzystywana w klasyfikacji dokumentów, gdzie każdy token reprezentuje cechę danych wejściowych klasyfikatora

In [68]:
# !pip install scikit-learn

In [91]:
from sklearn.feature_extraction.text import CountVectorizer

s = 'Well done is better than well said' # Benjamin Franklin
cv = CountVectorizer()
bow = cv.fit_transform([s])
cv.get_feature_names_out()

array(['better', 'done', 'is', 'said', 'than', 'well'], dtype=object)

In [70]:
bow.toarray()

array([[1, 1, 1, 1, 1, 2]])

In [71]:
df = pd.DataFrame(bow.toarray(), columns=cv.get_feature_names_out())
df

   better  done  is  said  than  well
0       1     1   1     1     1     2

Tworzenie reprezentacji dla wielu dokumentów

In [72]:
corpus = [
    'Well done is better than well said.', # Benjamin Franklin
    'Be yourself; everyone else is already taken.', # Oscar Wilde
    'Only a life lived for others is a life worthwhile.' # Albert Einstein
]

cv = CountVectorizer()
bow = cv.fit_transform(corpus)
cv.get_feature_names_out()

array(['already', 'be', 'better', 'done', 'else', 'everyone', 'for', 'is',
       'life', 'lived', 'only', 'others', 'said', 'taken', 'than', 'well',
       'worthwhile', 'yourself'], dtype=object)

In [73]:
bow.toarray()

array([[0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0]])

In [74]:
df = pd.DataFrame(bow.toarray(), columns=cv.get_feature_names_out())
pd.set_option('display.max_columns', 10)
df

,already,be,better,done,else,...,taken,than,well,worthwhile,yourself
0,0,0,1,1,0,...,0,1,2,0,0
1,1,1,0,0,1,...,1,0,0,0,1
2,0,0,0,0,0,...,0,0,0,1,0

Bardziej "oszczędna" wersja słownikowa:

In [75]:
# dla pierwszego wektora BoW w tabeli
i = 0
# indeksy tylko dodatnich wartości częstości
index = df.iloc[0,]>=1
# słownik dla pierwszego wektora BoW
dict(zip(df.columns[index], df.loc[i,index]))

{'better': 1, 'done': 1, 'is': 1, 'said': 1, 'than': 1, 'well': 2}

# Redukcja słownika

- Słownik (zbiór wszystkich tokenów) 
oznaczamy symbolem V 
- Rozmiar słownika  oznaczamy |V| 
- W obu omawianych reprezentacjach rozmiar 
słownika ma wpływ na rozmiar struktury danych

Aby zmniejszyć ten rozmiar stosuje się metody redukcji słownika minimalizujące utratę informacji:
- ujednolicanie wielkości liter
- Stemming
- lematyzację

## Ujednolicanie wielkości liter
zmiana na małe litery tylko pierwszego wyrazu w zdaniu

zaleta:
- zachowanie nazw własnych

wada:
- utrata informacji o nazwie własnej na pierwszej pozycji w zdaniu
- „Biedronka i Żabka konkurują w całej Polsce.”

In [76]:
s = 'The United Kingdom is a country in Northwestern Europe.'
s.lower()

'the united kingdom is a country in northwestern europe.'

## Stemming
- Stemming polega na usunięciu z wyrazu 
końcówki przy pozostawieniu tematu lub 
rdzenia
- Przykład: wyrazy program, programming, 
programmer, programs po zastosowaniu 
stemmingu sprowadzają się do słowa program

In [77]:
from nltk.tokenize import TreebankWordTokenizer
from nltk.stem.porter import PorterStemmer

s = 'The United Kingdom is a country in Europe'
tokenizer = TreebankWordTokenizer()
stemmer = PorterStemmer()
for t in tokenizer.tokenize(s):
    print(stemmer.stem(t), end=', ')

the, unit, kingdom, is, a, countri, in, europ,

# Lematyzacja
- Lematyzacja polega na grupowaniu słów odnoszących mających to samo lub podobne znaczenie (lemat)
- Lematyzator wykorzystuje wiedzę o synonimach słowa, jak np. WordNet

In [78]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\bathe\AppData\Roaming\nltk_data...

True

In [79]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

s = 'was are be were am'
tokenizer = TreebankWordTokenizer()
for t in tokenizer.tokenize(s):
    print(lemmatizer.lemmatize(t), end=', ')

wa, are, be, were, am,

In [80]:
for t in tokenizer.tokenize(s):
    print(lemmatizer.lemmatize(t, pos='v'), end=', ') # verb

be, be, be, be, be,

## Analiza sentymentu - VADER
- Wydźwięk (inaczej sentyment) niesie informację o emocjach, nastroju, opinii. 
- Celem analizy języka naturalnego często jest odczytanie emocjonalnej zawartości tekstu
- Metody analizy sentymentu można podzielić na:
    - słownikowe
    - statystyczne
- Słownikowe metody analizy sentymentu korzystają ze specjalnego słownika, który zawiera ocenę wyrazu
- Przykładem takiego słownika jest Valence Aware Dictionary and sEntiment Reasonerw skrócie VADER

Dane wejściowe:

In [92]:
# !pip install vaderSentiment

In [93]:
# "Joker: Folie à deux" user reviews from IMDB
# 5/10 stars  https://www.imdb.com/review/rw10050802/?ref_=tt_urv
s1 = '''Joker 2 is a massive disappointment when compared to the brilliance of the first film. The decision to turn what was initially a dark, psychological character study into a musical is baffling and completely undermines the tone that made the original so powerful. The musical numbers feel out of place and detract from the raw, gritty world that was built in Joker 1. What's even worse is that the spotlight shifts almost entirely from the Joker himself to Lady Gaga, making it feel less like a Joker movie and more like a Lady Gaga showcase.
In Joker 1, there was a subtle yet significant tie to the larger Batman universe, with references to Bruce Wayne and Gotham City that added depth and context to Arthur Fleck's descent into madness. However, Joker 2 abandons all of that, losing any connection to the broader world that could have made the story more meaningful. The film's narrative becomes so centered on Gaga's character that it might as well have been titled Lady Gaga, not Joker.
The only saving grace of this movie is Joaquin Phoenix's incredible performance as the Joker. His portrayal is once again mesmerizing, showing the tortured and chaotic nature of the character. But even Phoenix's brilliance can't save a film that feels disjointed, tonally confused, and lacking the substance that made the first one so iconic.'''
# 1/10 stars https://www.imdb.com/review/rw10042578/?ref_=tt_urv
s2 = '''I'm so irritated. "Joker" was a gritty, intense psychological thriller that explored complex themes of mental illness and societal breakdown. It was a raw, dark film that didn't need gimmicks or unnecessary changes to make a statement. So WHY in the world would anyone think it's a good idea to turn "Joker 2" into a musical?
This is a slap in the face to fans of the original. We didn't ask for dancing and singing - we wanted more of the same unsettling atmosphere, not a Broadway-style number in the middle of Gotham's madness. I signed up for a continuation of Arthur Fleck's descent into chaos, not a flashy musical break that completely destroys the tone.
The first "Joker" was a masterpiece. This sequel choice feels like a desperate attempt to be "different" without respecting the core of what made the character and story so compelling. Ridiculous decision.'''
# 10/10 stars https://www.imdb.com/review/rw10051292/?ref_=tt_urv
s3 = '''I have seen a lot of peoples bad reviews, and I get why typical comic/marvel fans don't like this movie. For people who like more cookie-cutter plots and familiar storylines, this movie will disappoint. I however, loved it! This is good art, every scene is masterfully shot, and the theme in the movie plays deeply on emotions. Acting is just fantastic. I cried, laughed and sat with an open jaw, just amazed by how the movie is filmed, how every scene was so beautifully put together. I generally don't like musicals, but in this movie it just works.
For people more mentally oriented, worrying about how this movie connects to other DC movies and want to feel the same generic and familiar theme as most other comic movies - this is not for you. The emotional story is part of this movies genius, filled with deep empathy, love, sadness, vulnerability and joy.'''


SentimentIntensityAnalyzer zwraca 4 oceny 
tekstu:
- negatywną (neg)
- neutralną (neu)
- pozytywną (pos)
- złożoną (compound)

In [94]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()
sia.polarity_scores(s1)

{'neg': 0.099, 'neu': 0.779, 'pos': 0.121, 'compound': 0.1484}

In [95]:
sia.polarity_scores(s2)

{'neg': 0.144, 'neu': 0.724, 'pos': 0.132, 'compound': -0.7223}

In [96]:
sia.polarity_scores(s3)

{'neg': 0.103, 'neu': 0.724, 'pos': 0.173, 'compound': 0.9162}

In [97]:
tokens = [':)', ':-)', ":'-(", 'lol', 'bff', 'idk', 'meh', 'cutie']
for t in tokens:
    print(f'"{t}" compound score = {sia.lexicon[t]}')

":)" compound score = 2.0
":-)" compound score = 1.3
":'-(" compound score = -2.4
"lol" compound score = 1.8
"bff" compound score = 2.9
"idk" compound score = -0.4
"meh" compound score = -0.3
"cutie" compound score = 1.5